name: Build Windows Forms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar o .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x # Se o seu projeto for .NET 6 ou 7, mude aqui

    - name: Restaurar pacotes (NuGet)
      run: dotnet restore

    - name: Compilar o projeto (Build)
      run: dotnet build --configuration Release --no-restore
